const videoArray = [
  {
    videoId: 23455,
    thumbnailUrl: "https://i.ytimg.com/vi/eE6u67Ph768/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/watch?v=eE6u67Ph768",
    duration: 30.2,
    category: "investing",
    title: "Cathie Wood - Investing in disruptive innovation",
    creator: "Singularity University",
    views: "2245",
  },
  {
    videoId: 23456,
    thumbnailUrl: "https://i.ytimg.com/vi/03gRoHXwoVY/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/watch?v=03gRoHXwoVY&t=354s",
    duration: 28.29,
    category: "trading",
    title: "Linda Raschke's Edge In Trading",
    creator: "Anthony Crudele",
    views: "2245",
  },
  {
    videoId: 23457,
    thumbnailUrl: "https://i.ytimg.com/vi/PHe0bXAIuk0/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/watch?v=PHe0bXAIuk0&t=7s",
    duration: 30.59,
    category: "economy",

    title: "How The Economic Machine Works by Ray Dalio",
    creator: "Ray Dalio",
    views: "2245",
  },
  {
    videoId: 23458,
    thumbnailUrl: "https://i.ytimg.com/vi/fTTGALaRZoc/sddefault.jpg",
    videoUrl: "https://www.youtube.com/watch?v=fTTGALaRZoc",
    duration: 30.45,
    category: "economy",
    title: "Banking Explained - Money and Credit",
    creator: "Kurzgesat",
    views: "2245",
  },
  {
    videoId: 23459,
    thumbnailUrl: "https://i.ytimg.com/vi/CC9VeHrI3Es/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/watch?v=CC9VeHrI3Es",
    duration: 4.26,
    category: "trading",
    title: "Futures Market Explained",
    creator: "Harvest Public Media",
    views: "2245",
  },
  {
    videoId: 23460,
    thumbnailUrl: "https://i.ytimg.com/vi/CAs_aX95tVQ/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/watch?v=CAs_aX95tVQ",
    duration: 9.41,
    category: "trading",
    title: "How Short Selling Works",
    creator: "The Plain Bagel",
    views: "2245",
  },

  {
    videoId: 23461,
    thumbnailUrl: "https://i.ytimg.com/vi/krynBQZtsuM/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/watch?v=krynBQZtsuM",
    duration: 8.47,
    category: "economy",
    title: "Why a strong dollar isn't as good as you think",
    creator: "CNBC",
    views: "2245",
  },
  {
    videoId: 23462,
    thumbnailUrl: "https://i.ytimg.com/vi/HrVgUmrxx00/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/watch?v=HrVgUmrxx00",
    duration: 103.1,
    category: "investing",
    title: "INVESTING IN MICRO-CAPS IN THE US MARKET",
    creator: "Omkara",
    views: "2245",
  },
  {
    videoId: 23463,
    thumbnailUrl: "https://i.ytimg.com/vi/5z4q7NdmK3U/sddefault.jpg",
    videoUrl: "https://www.youtube.com/watch?v=5z4q7NdmK3U",
    duration: 120,
    category: "investing",
    title: "The World of Industrial Automation",
    creator: "PPFAS",
    views: "2245",
  },
  {
    videoId: 23464,
    thumbnailUrl: "https://i.ytimg.com/vi/6_CWubvfQVU/sddefault.jpg",
    videoUrl: "https://www.youtube.com/watch?v=6_CWubvfQVU",
    duration: 48,
    category: "investing",
    title: "Understanding Hospital Industry in India",
    creator: "PPFAS",
    views: "2245",
  },
  {
    videoId: 23465,
    thumbnailUrl: "https://i.ytimg.com/vi/qdI_XlSrPMs/sddefault.jpg",
    videoUrl: "https://www.youtube.com/watch?v=qdI_XlSrPMs",
    duration: 3.45,
    category: "investing",
    title: "Food Services Industry in India",
    creator: "PPFAS",
    views: "2245",
  },
  {
    videoId: 23466,
    thumbnailUrl: "https://i.ytimg.com/vi/Xq0ZxJRaaAg/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/watch?v=Xq0ZxJRaaAg",
    duration: 1,
    category: "economy",
    title: "Inflation, deflation, and disinflation",
    creator: "Yahoo Finance",
    views: "2245",
  },
  {
    videoId: 23467,
    thumbnailUrl: "https://i.ytimg.com/vi/dwLkGbu4Mq8/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/watch?v=dwLkGbu4Mq8",
    duration: 15.44,
    category: "investing",
    title: "Learn the Basics of Investing",
    creator: "Shankar Nath",
    views: "2245",
  },
  {
    videoId: 23468,
    thumbnailUrl: "https://i.ytimg.com/vi/MhwrQpXQq4I/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/watch?v=MhwrQpXQq4I",
    duration: 4.15,
    category: "trading",
    title: "What is Arbitrage ?",
    creator: "Academy",
    views: "2245",
  },
  {
    videoId: 23469,
    thumbnailUrl: "https://i.ytimg.com/vi/PSrC-5ye4V0/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/watch?v=PSrC-5ye4V0",
    duration: 5.12,
    category: "economy",
    title: "Currency Manipulation",
    creator: "Marginal Revolution",
    views: "2245",
  },
];

module.exports = videoArray;
